# Generated by Django 3.2 on 2022-07-29 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_alter_recipe_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='fav_total',
            field=models.IntegerField(default=0),
        ),
    ]
