# Generated by Django 3.2 on 2022-07-29 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_recipe_fav_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='fav_total',
        ),
    ]
