name: Foodgram worklfow

on: [push]

jobs:

  build_and_push_to_docker_hub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2 
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1 
      - name: Login to Docker
        uses: docker/login-action@v1 
        with:
          username: kazhuha
          password: SMOY5plol-yon1zar
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2 
        with:
          context: backend/receptorium
          push: true
          tags: kazhuha/receptorium:latest